// src/components/solutions.vue
<template>
    <div class='solutions-wrapper'>
        <div
                v-for='(result, index) in results'
                :key='index'>
            <p
                    class='solution'
                    @click='copy'
                    v-if='result && typeof result !== "function"'>
                {{ result }}
            </p>
            <br v-else>
            <div class='clear'></div>
        </div>
    </div>
</template>

<script>
import { clipboard } from 'electron';
import { evaluate } from 'mathjs';

export default {
    name: 'solutions',
    computed: {
        results() {
            const state = {};
            const output = [];
            const input = this.$store.state.input.split('\n');
            input.forEach(line => {
                let solution;
                try {
                    solution = evaluate(line, state) || '';
                } catch (e) { /* do nothing */ }
                output.push(solution);
            });
            return output;
        }
    },
    methods: {
        copy: (event) => {
            const text = event.target.innerText;
            clipboard.writeText(text);
        }
    }
};
</script>

// src/components/Solutions.jsx
// import { clipboard } from 'electron';
import { evaluate } from 'mathjs';
import { useContext } from 'react';

import { AppContext } from '../App';

import './Solutions.css';

function copyEvent(event) {
  console.log(event.target.innerText);
  // const text = event.target.innerText;
  // clipboard.writeText(text);
}

function Solutions() {
  const { state } = useContext(AppContext);
  const scope = {};
  const solutions = [];
  const lines = state.text.split('\n');

  for (const [index, line] of lines.entries()) {
    let solution;
    try {
        solution = evaluate(line, scope);
        solution = (typeof solution == 'number')
          ? Math.round(solution * 100) / 100
          : JSON.stringify(solution);
    } catch (e) { /* do nothing */ }
    solutions.push(
      <div key={ index } className='ellipsis solution-wrapper'>
        <p className='solution' onClick={ copyEvent }>{ solution }</p>
      </div>
    );
  }

  return <>{ solutions }</>;
}

export default Solutions;
